# 字符串相似性计算

Similarity String Handling

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics.pairwise import cosine_similarity
data = ["This is some sample data",
        "This is some example data",
        "This is some example data",
        "More sample data",
        "Another example"]
# 数据矢量化
vectorizer = TfidfVectorizer ()
vectors = vectorizer.fit_transform(data)
# 计算余弦相似度
similarities = cosine_similarity(vectors)
# 查找重复
duplicates = set ()
for i in range (len(similarities)):
    for j in range(i+1, len(similarities)):
        if similarities[i][j] > 0.95:
            duplicates.add (j)
# 删除重复内容
for i in sorted (duplicates, reverse=True):
    del data[i]
print(data)

['This is some sample data', 'This is some example data', 'More sample data', 'Another example']


In [ ]:
import pandas as pd

df = pd.read_csv('data/MotorcycleData.csv',encoding = 'utf-8',dtype =str)

from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics.pairwise import cosine_similarity

data = pd.Series(df['Location']).to_numpy()
# 数据矢量化
vectorizer = TfidfVectorizer ()
vectors = vectorizer.fit_transform(data.astype('U'))
# 计算余弦相似度
similarities = cosine_similarity(vectors)
print(similarities)
# 查找重复
duplicates=set()
for i in range (len(similarities)):
    for j in range(i+1, len(similarities)):
        if similarities[i][j] > 0.95:
            duplicates.add (j)
# 删除重复内容
print(duplicates)
df.drop(index=duplicates,inplace=True)
print(df)

[[1.         0.02665852 0.30393068 ... 0.04434518 0.03041982 0.02982183]
 [0.02665852 1.         0.02551972 ... 0.02993275 0.0205332  0.02012957]
 [0.30393068 0.02551972 1.         ... 0.04245084 0.02912034 0.0285479 ]
 ...
 [0.04434518 0.02993275 0.04245084 ... 1.         0.03415601 0.03348457]
 [0.03041982 0.0205332  0.02912034 ... 0.03415601 1.         0.02296968]
 [0.02982183 0.02012957 0.0285479  ... 0.03348457 0.02296968 1.        ]]
{9, 10, 23, 25, 28, 29, 46, 57, 62, 63, 64, 67, 70, 77, 83, 93, 98, 103, 105, 107, 109, 114, 117, 124, 129, 131, 132, 133, 137, 139, 143, 146, 147, 150, 152, 154, 155, 156, 157, 160, 164, 165, 172, 173, 177, 178, 185, 186, 193, 195, 197, 199, 201, 202, 203, 204, 205, 208, 215, 219, 223, 224, 226, 227, 228, 231, 232, 235, 236, 237, 240, 241, 244, 245, 246, 250, 251, 252, 255, 260, 261, 262, 264, 265, 267, 268, 269, 270, 275, 277, 279, 281, 282, 283, 285, 288, 292, 294, 295, 296, 300, 301, 306, 308, 309, 311, 313, 315, 316, 324, 331, 339, 340, 346, 350

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity  
from sklearn.feature_extraction.text import TfidfVectorizer  
  
# 假设我们有两个文本  
text1 = "This is the first document."  
text2 = "This document is the second document."
text3 = "This document is the second document."    
  
# 使用TF-IDF向量化器将文本转换为向量  
vectorizer = TfidfVectorizer().fit_transform([text1, text2, text3])  
  
# 计算余弦相似度  
cosine_sim = cosine_similarity(vectorizer[0:1], vectorizer[2:3])  
print(f"Cosine Similarity: {cosine_sim[0][0]}")

In [ ]:
import nltk
from nltk.metrics import edit_distance

str1 = "kitten"
str2 = "sitting"
distance = edit_distance(str1, str2)
print(distance)

In [ ]:
import numpy as np
import pandas as pd

def cosine_similarity(df):
    """
    计算数据帧中每行之间的余弦相似度
    """
    # 计算每一行的L2范数
    norms = df.apply(np.linalg.norm, axis=1)

    # 计算余弦相似度
    cosine_sim = df.dot(df.T).divide(np.outer(norms, norms))

    # 将对角线设置为NaN，因为每行与自己的余弦相似度为1
    np.fill_diagonal(cosine_sim.values, np.nan)

    # 将余弦相似度存储在数据框中
    sim_df = pd.DataFrame(cosine_sim.values, index=df.index, columns=df.index)

    return sim_df

# 示例电影评分数据集
ratings_df = pd.DataFrame({
    'user0': [3, 1, 2, 0, 2],
    'user1': [1, 3, 4, 1, 0],
    'user2': [2, 4, 4, 1, 1],
    'user3': [1, 2, 1, 3, 4],
    'user4': [4, 1, 3, 2, 0]
}, index=['movie0', 'movie1', 'movie2', 'movie3', 'movie4'])

# 计算每个用户之间的余弦相似度
similarity_df = cosine_similarity(ratings_df)
print(similarity_df.head(10))
print(ratings_df.head(10))


In [ ]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import cosine

data = pd.read_csv('data/online_order.csv')
print(data.head())

def cosine_sim(row1, row2):
    return 1 - cosine(row1, row2)

data['similarity'] = data.apply(lambda row: data.apply(lambda other_row: cosine_sim(row, other_row), axis=1), axis=1)

def most_similar(row, n):
    return row.sort_values(ascending=False)[:n]

data.apply(lambda row: most_similar(row, 3), axis=1)



# 余弦相似度

In [ ]:
import numpy as np

def cosine_similarity(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    norm_vector1 = np.linalg.norm(vector1)
    norm_vector2 = np.linalg.norm(vector2)
    return dot_product / (norm_vector1 * norm_vector2)

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
similarity = cosine_similarity(vector1, vector2)

print(f"余弦相似度: {similarity}")

# 欧氏距离

In [ ]:
import numpy as np

def euclidean_distance(vector1, vector2):
    return np.linalg.norm(vector1 - vector2)

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

distance = euclidean_distance(vector1, vector2)

print(f"欧氏距离: {distance}")

In [ ]:
import numpy as np

def manhattan_distance(vector1, vector2):
    return np.sum(np.abs(vector1 - vector2))

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

distance = manhattan_distance(vector1, vector2)

print(f"曼哈顿距离: {distance}")